# Site settings
title: Life Goals
description: Motivational Quotes 
keywords: Motivation Quotes, Author Quotes, Fun
author: Amin Sati
baseurl: "https://motivationlifegoal.github.io/" # the subpath of your site, e.g. /blog/
url: "https://motivationlifegoal.github.io/" # the base hostname & protocol for your site
